// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHSf6SLLVL3eQ5EV0r5u9yIKzoWVFRjhc',
    appId: '1:477521001950:web:89dc7c9a5a72b88c75b14f',
    messagingSenderId: '477521001950',
    projectId: 'dividendrad',
    authDomain: 'dividendrad.firebaseapp.com',
    storageBucket: 'dividendrad.firebasestorage.app',
    measurementId: 'G-D33840TCR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv1Qq5WyahkSNew_5-t3A6XTS91a5TEA0',
    appId: '1:477521001950:android:bfb8fa596a53e34275b14f',
    messagingSenderId: '477521001950',
    projectId: 'dividendrad',
    storageBucket: 'dividendrad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6CchAqoUXE23baDPgJOcuI7SLvgA2Y3c',
    appId: '1:477521001950:ios:37a124c910c9b26175b14f',
    messagingSenderId: '477521001950',
    projectId: 'dividendrad',
    storageBucket: 'dividendrad.firebasestorage.app',
    iosBundleId: 'com.example.dividendradar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6CchAqoUXE23baDPgJOcuI7SLvgA2Y3c',
    appId: '1:477521001950:ios:37a124c910c9b26175b14f',
    messagingSenderId: '477521001950',
    projectId: 'dividendrad',
    storageBucket: 'dividendrad.firebasestorage.app',
    iosBundleId: 'com.example.dividendradar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHSf6SLLVL3eQ5EV0r5u9yIKzoWVFRjhc',
    appId: '1:477521001950:web:42268aa6a7d5d64075b14f',
    messagingSenderId: '477521001950',
    projectId: 'dividendrad',
    authDomain: 'dividendrad.firebaseapp.com',
    storageBucket: 'dividendrad.firebasestorage.app',
    measurementId: 'G-C57TMRMX5B',
  );
}
